<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Preface" data-toc-modified-id="Preface-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Preface</a></span><ul class="toc-item"><li><span><a href="#Description" data-toc-modified-id="Description-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Description</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Get-the-database-config" data-toc-modified-id="Get-the-database-config-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Get the database config</a></span></li><li><span><a href="#Load-sql-magic" data-toc-modified-id="Load-sql-magic-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Load sql magic</a></span></li><li><span><a href="#Get-names-of-all-tables" data-toc-modified-id="Get-names-of-all-tables-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Get names of all tables</a></span></li><li><span><a href="#Connect-the-mysql-server" data-toc-modified-id="Connect-the-mysql-server-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Connect the mysql server</a></span></li><li><span><a href="#Avoid-1055-error" data-toc-modified-id="Avoid-1055-error-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Avoid 1055 error</a></span></li></ul></li><li><span><a href="#SQL-Subqueries" data-toc-modified-id="SQL-Subqueries-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>SQL Subqueries</a></span><ul class="toc-item"><li><span><a href="#Exercise-1" data-toc-modified-id="Exercise-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Exercise 1</a></span><ul class="toc-item"><li><span><a href="#Exercise-1" data-toc-modified-id="Exercise-1-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Exercise 1</a></span></li><li><span><a href="#Exercise-2" data-toc-modified-id="Exercise-2-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Exercise 2</a></span></li><li><span><a href="#Exercise-3" data-toc-modified-id="Exercise-3-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>Exercise 3</a></span></li></ul></li></ul></li><li><span><a href="#SELF-JOIN" data-toc-modified-id="SELF-JOIN-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>SELF JOIN</a></span></li><li><span><a href="#Views" data-toc-modified-id="Views-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Views</a></span><ul class="toc-item"><li><span><a href="#Exercise-1" data-toc-modified-id="Exercise-1-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Exercise 1</a></span></li></ul></li></ul></div>

# Preface

## Description
**Notes**  
- Mysql is case insensitive. eg `like('m%')` and `like('M%')` are same.


Entity Relation (ER) Diagram:

![](pdf/employees_db.png)

## Imports

In [1]:
import numpy as np
import pandas as pd
import os
import json

## Get the database config

In [2]:
ifile = os.path.expanduser('~') + "/.mysql_conf.json"
with open(ifile) as fo:
    data = json.load(fo)
    
pw = data['password']

## Load sql magic

In [3]:
%load_ext sql

In [4]:
%sql mysql+mysqlconnector://bhishan:$pw@localhost/employees

'Connected: bhishan@employees'

## Get names of all tables

In [5]:
%%sql
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'employees';

 * mysql+mysqlconnector://bhishan:***@localhost/employees
10 rows affected.


[('current_dept_emp',),
 ('departments',),
 ('departments_dup',),
 ('dept_emp',),
 ('dept_emp_latest_date',),
 ('dept_manager',),
 ('dept_manager_dup',),
 ('employees',),
 ('salaries',),
 ('titles',)]

## Connect the mysql server

In [6]:
import mysql.connector

conn = mysql.connector.connect(
    host='localhost',user='bhishan',passwd=pw,database='employees')

cur = conn.cursor()

In [7]:
%sql select * from dept_manager limit 2;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(110022, 'd001', datetime.date(1985, 1, 1), datetime.date(1991, 10, 1)),
 (110039, 'd001', datetime.date(1991, 10, 1), datetime.date(9999, 1, 1))]

## Avoid 1055 error

In [8]:
q = "set @@global.sql_mode := replace(@@global.sql_mode, 'ONLY_FULL_GROUP_BY', '');"
cur.execute(q)
conn.commit()

# SQL Subqueries

## Exercise 1
Extract the information about all department managers who were hired between the 1st of January 1990 and the 1st of January 1995.

In [9]:
%%sql
SELECT *
FROM dept_manager
WHERE emp_no IN
    (SELECT emp_no
     FROM employees
     WHERE hire_date BETWEEN '1990-01-01' AND '1995-01-01');

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(110420, 'd004', datetime.date(1996, 8, 30), datetime.date(9999, 1, 1)),
 (111877, 'd009', datetime.date(1992, 9, 8), datetime.date(1996, 1, 3))]

## EXISTS and NOT EXISTS

### Exercise 1

Select the entire information for all employees whose job title is “Assistant Engineer”. 

In [11]:
%%sql
SELECT *
FROM employees e
WHERE EXISTS
    (SELECT *
     FROM titles t
     WHERE t.emp_no = e.emp_no
       AND title = 'Assistant Engineer')
LIMIT 2;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(10008, datetime.date(1958, 2, 19), 'Saniya', 'Kalloufi', 'M', datetime.date(1994, 9, 15)),
 (10009, datetime.date(1952, 4, 19), 'Sumant', 'Peac', 'F', datetime.date(1985, 2, 18))]

### Exercise 2
Starting your code with “DROP TABLE”, create a table called “emp_manager” (emp_no – integer of 11, not null; dept_no – CHAR of 4, null; manager_no – integer of 11, not null). 

In [12]:
q = """\
DROP TABLE IF EXISTS emp_manager;
""";
cur.execute(q)

In [13]:
q = """\
CREATE TABLE emp_manager (

  emp_no INT(11) NOT NULL,

  dept_no CHAR(4) NULL,

  manager_no INT(11) NOT NULL

);
""";
cur.execute(q)
conn.commit()

### Exercise 3
Fill emp_manager with data about employees, the number of the department they are working in, and their managers.

Your query skeleton must be:

Insert INTO emp_manager SELECT

U.*

FROM

                (A)

UNION (B) UNION (C) UNION (D) AS U;

A and B should be the same subsets used in the last lecture (SQL Subqueries Nested in SELECT and FROM). In other words, assign employee number 110022 as a manager to all employees from 10001 to 10020 (this must be subset A), and employee number 110039 as a manager to all employees from 10021 to 10040 (this must be subset B).

Use the structure of subset A to create subset C, where you must assign employee number 110039 as a manager to employee 110022.

Following the same logic, create subset D. Here you must do the opposite - assign employee 110022 as a manager to employee 110039.

Your output must contain 42 rows.

In [14]:
%%sql
INSERT INTO emp_manager
SELECT 
    u.*
FROM
    (SELECT 
        a.*
    FROM
        (SELECT 
        e.emp_no AS employee_ID,
            MIN(de.dept_no) AS department_code,
            (SELECT 
                    emp_no
                FROM
                    dept_manager
                WHERE
                    emp_no = 110022) AS manager_ID
    FROM
        employees e
    JOIN dept_emp de ON e.emp_no = de.emp_no
    WHERE
        e.emp_no <= 10020
    GROUP BY e.emp_no
    ORDER BY e.emp_no) AS a UNION SELECT 
        b.*
    FROM
        (SELECT 
        e.emp_no AS employee_ID,
            MIN(de.dept_no) AS department_code,
            (SELECT 
                    emp_no
                FROM
                    dept_manager
                WHERE
                    emp_no = 110039) AS manager_ID
    FROM
        employees e
    JOIN dept_emp de ON e.emp_no = de.emp_no
    WHERE
        e.emp_no > 10020
    GROUP BY e.emp_no
    ORDER BY e.emp_no
    LIMIT 20) AS b UNION SELECT 
        c.*
    FROM
        (SELECT 
        e.emp_no AS employee_ID,
            MIN(de.dept_no) AS department_code,
            (SELECT 
                    emp_no
                FROM
                    dept_manager
                WHERE
                    emp_no = 110039) AS manager_ID
    FROM
        employees e
    JOIN dept_emp de ON e.emp_no = de.emp_no
    WHERE
        e.emp_no = 110022
    GROUP BY e.emp_no) AS c UNION SELECT 
        d.*
    FROM
        (SELECT 
        e.emp_no AS employee_ID,
            MIN(de.dept_no) AS department_code,
            (SELECT 
                    emp_no
                FROM
                    dept_manager
                WHERE
                    emp_no = 110022) AS manager_ID
    FROM
        employees e
    JOIN dept_emp de ON e.emp_no = de.emp_no
    WHERE
        e.emp_no = 110039
    GROUP BY e.emp_no) AS d) as u;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
42 rows affected.


[]

In [16]:
%sql select * from emp_manager limit 2;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(10001, 'd005', 110022), (10002, 'd007', 110022)]

In [17]:
%sql select count(*) from emp_manager;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
1 rows affected.


[(42,)]

# SELF JOIN

In [25]:
%%sql
-- this does not work
select distinct *
from emp_manager
where emp_no = manager_no;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
0 rows affected.


[]

In [21]:
%%sql
select distinct e1.*
from emp_manager e1
join emp_manager e2
on e1.emp_no = e2.manager_no;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(110022, 'd001', 110039), (110039, 'd001', 110022)]

In [23]:
%%sql
select e1.*
from emp_manager e1
join emp_manager e2
on e1.emp_no = e2.manager_no
where e2.emp_no in ( select manager_no from emp_manager);

 * mysql+mysqlconnector://bhishan:***@localhost/employees
2 rows affected.


[(110039, 'd001', 110022), (110022, 'd001', 110039)]

# Views

## Exercise 1

Create a view that will extract the average salary of all managers registered in the database. Round this value to the nearest cent.

If you have worked correctly, after executing the view from the “Schemas” section in Workbench, you should obtain the value of 66924.27.

In [26]:
%%sql
CREATE OR REPLACE VIEW v_manager_avg_salary AS
SELECT ROUND(AVG(salary), 2)
FROM salaries s
JOIN dept_manager m ON s.emp_no = m.emp_no;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
0 rows affected.


[]

In [29]:
"""
Go to workbench as look at views, we can see new view.

Note: view is dynamic, if the table is updated, views are updated automatically.

We can not insert or update view, only can view them.

""";

In [28]:
%sql select * from employees.v_manager_avg_salary;

 * mysql+mysqlconnector://bhishan:***@localhost/employees
1 rows affected.


[(Decimal('66924.27'),)]